# Font
font_family      FiraCode Nerd Font Mono
bold_font        auto
italic_font      auto
font_size        14.0

# Cursor
cursor_shape            block
cursor_blink_interval   0

# Scrollback
scrollback_lines 10000

# Performance
enable_audio_bell no

# Window
window_padding_width    8
background_opacity      1

# Tabs
tab_bar_edge    bottom
tab_bar_style   powerline

# Colors
include themes/orca-dark.conf

# Window split keybindings
# map f4 launch --cwd=current --location=split
# map f5 launch --cwd=current --location=hsplit
# map f6 launch --cwd=current --location=vsplit
# map f7 layout_action rotate
