# Background / foreground
background #22272e
foreground #adbac7

# Cursor
cursor #adbac7

# Selection
selection_background #444c56
selection_foreground #adbac7

# Black
color0  #545d68
color8  #636e7b

# Red
color1  #f47067
color9  #ff7b72

# Green
color2  #8ddb8c
color10 #b4f1b4

# Yellow
color3  #f69d50
color11 #f2cc60

# Blue
color4  #6cb6ff
color12 #96d0ff

# Magenta
color5  #dcbdfb
color13 #e6ccff

# Cyan
color6  #96d0ff
color14 #b6e3ff

# White
color7  #adbac7
color15 #ffffff
