# Orca-inspired dark palette
background #0a0a0a
foreground #fafafa

# Cursor
cursor #fafafa

# Selection
selection_background #404040
selection_foreground #fafafa

# Black
color0  #404040
color8  #737373

# Red
color1  #ff6568
color9  #ff8587

# Green
color2  #86efac
color10 #a7f3c0

# Yellow
color3  #fbbf24
color11 #fcd267

# Blue
color4  #3794ff
color12 #6eb2ff

# Magenta
color5  #b66dff
color13 #cd9bff

# Cyan
color6  #40b0a6
color14 #75c9c1

# White
color7  #a1a1a1
color15 #fafafa
